repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.3
    hooks:
      - id: ruff
        args:
          - --fix
          - --unsafe-fixes
          - --exit-zero
          - --select=E,F,I,UP
        exclude: \.ipynb$
      - id: ruff-format
        exclude: \.ipynb$
  - repo: https://github.com/sidnb13/toolbox
    rev: ai-commit-v0.1.0.dev1
    hooks:
      - id: ai-commit
        name: ai-commit
        entry: ai-commit
        language: python
        stages: [commit-msg]
