seed: 42

batch_size: 128
gradient_accumulation_steps: 1
num_examples_per_task_train: 10000
num_examples_per_task_val: 500
num_examples_per_task_test: 1000
lr: 0.001
opt_type: adam
# Number of epochs to train (used if steps == -1)
epochs: 10
# Number of steps to train (if > 0, overrides epochs)
steps: -1
max_grad_norm: 1.0
device: mps

wandb:
  log: true
  project: mixed_batching
  entity: ${oc.env:WANDB_ENTITY,null}
  run_name: ${oc.env:WANDB_RUN_NAME,null}
  run_id: ${oc.env:WANDB_RUN_ID,null}
  group: ${oc.env:WANDB_GROUP,null}
  tags: ${oc.env:WANDB_TAGS,null}
  notes: ${oc.env:WANDB_NOTES,null}

# Task setup
train_mode: sequential # mixed_batch, sequential
num_tasks: 10
val_interval: 100  # Validate every 100 steps

n_features: 20
hidden_dim: 64
assets_dir: assets  # Directory to save plots and other assets

profile_interval: 1000  # Run profiling every 1000 steps

profiler_dir: profiler_traces  # Directory for torch.profiler traces